# Generated by Django 3.1 on 2020-08-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_medicalform_medicalformattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalformattribute',
            name='attribute_option',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
