# Generated by Django 3.1 on 2020-08-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_auto_20200818_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalformattribute',
            name='attribute_option',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
