# Generated by Django 3.1 on 2020-08-18 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_auto_20200818_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalFormAndAttributeRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.CharField(default='Y', max_length=1)),
                ('active', models.CharField(default='Y', max_length=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.medicalformattribute')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.medicalform')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalFormAttributeFilld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.CharField(default='Y', max_length=1)),
                ('active', models.CharField(default='Y', max_length=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('form_attribute_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.medicalformandattributerelation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.medicalform')),
            ],
        ),
    ]
