# Generated by Django 3.1 on 2020-08-19 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_medicalformandattributerelation_medicalformattributefilld'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalFormAttributeFilld',
        ),
    ]
