# Generated by Django 3.1 on 2020-09-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_clinicadmin_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicprofile',
            name='clinic_description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
