# Generated by Django 3.1 on 2020-09-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_assistantprofile_white_list_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantprofile',
            name='white_list_ip',
            field=models.CharField(default='*', max_length=200),
        ),
    ]
