# Generated by Django 3.1 on 2020-08-12 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctorprofile_is_email_validated'),
        ('clinic', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='address',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='home_contact',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='is_email_validated',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='postalcode',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='profile_pic',
            field=models.CharField(default='user_default_pic.png', max_length=100),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='work_contact',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='PatientDoctorRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(null=True)),
                ('doctor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorprofile')),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PatientClinicRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(null=True)),
                ('clinic_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.clinicprofile')),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientprofile')),
            ],
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='clinic_profile',
            field=models.ManyToManyField(through='patient.PatientClinicRelation', to='clinic.ClinicProfile'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='doctor_profile',
            field=models.ManyToManyField(through='patient.PatientDoctorRelation', to='doctor.DoctorProfile'),
        ),
    ]
