# Generated by Django 3.1 on 2020-08-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_medicalformattributefilled'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalformattributefilled',
            name='filled_value',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
