# Generated by Django 3.1 on 2020-09-19 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinic', '0008_clinicadmin_profile_pic'),
        ('patient', '0005_medicalformattributefilled_filled_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalFormAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.CharField(default='Y', max_length=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('medical_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.medicalform')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
