# Generated by Django 3.1 on 2020-08-12 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorClinicRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('join_date', models.DateTimeField(null=True)),
                ('leave_date', models.DateTimeField(null=True)),
                ('clinic_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.clinicprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorOccupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorOccupationRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.CharField(default='user_default_pic.png', max_length=100)),
                ('practice_start_date', models.DateField(null=True)),
                ('description', models.TextField(max_length=2000, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('active', models.CharField(default='Y', max_length=1)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('clinic_profile', models.ManyToManyField(through='doctor.DoctorClinicRelation', to='clinic.ClinicProfile')),
                ('occupation', models.ManyToManyField(through='doctor.DoctorOccupationRelation', to='doctor.DoctorOccupation')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorQualificationRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorprofile')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorqualification')),
            ],
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='qualification',
            field=models.ManyToManyField(through='doctor.DoctorQualificationRelation', to='doctor.DoctorQualification'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctoroccupationrelation',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorprofile'),
        ),
        migrations.AddField(
            model_name='doctoroccupationrelation',
            name='occupation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctoroccupation'),
        ),
        migrations.AddField(
            model_name='doctorclinicrelation',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorprofile'),
        ),
    ]
