# Generated by Django 3.1 on 2020-09-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0002_auto_20200925_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionistprofile',
            name='white_list_ip',
            field=models.CharField(default='*', max_length=10),
        ),
    ]
